# Generated by Django 3.2 on 2021-12-15 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order', models.AutoField(primary_key=True, serialize=False)),
                ('add_from_another_strategy', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('index_name', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('flag', models.CharField(blank=True, choices=[('create_rule', 'create_rule'), ('strategy', 'strategy')], default='create_rule', max_length=250, null=True)),
                ('total', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rule',
                'verbose_name_plural': 'Rules',
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('rules', models.ManyToManyField(related_name='strategies', through='rule.Order', to='rule.Rule')),
            ],
            options={
                'verbose_name': 'Strategy',
                'verbose_name_plural': 'Strategies',
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_category', models.CharField(choices=[('any', 'any'), ('process', 'process'), ('network', 'network'), ('file', 'file'), ('registry', 'registry'), ('authentication', 'authentication'), ('configuration', 'configuration'), ('database', 'database'), ('driver', 'driver'), ('host', 'host'), ('iam', 'iam'), ('intrusion_detection', 'intrusion_detection'), ('malware', 'malware'), ('package', 'package'), ('session', 'session'), ('threat', 'threat'), ('web', 'web')], default='any', max_length=32)),
                ('condition', models.CharField(max_length=200)),
                ('by', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='rule.rule')),
            ],
            options={
                'verbose_name': 'Query',
                'verbose_name_plural': 'Queries',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='add_strategy',
            field=models.ManyToManyField(blank=True, to='rule.Strategy'),
        ),
        migrations.AddField(
            model_name='order',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rule.rule'),
        ),
        migrations.AddField(
            model_name='order',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stra', to='rule.strategy'),
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.BooleanField(default=False)),
                ('until', models.BooleanField(default=False)),
                ('maxspan', models.BooleanField(default=False)),
                ('size', models.BooleanField(default=False)),
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='rule.rule')),
            ],
        ),
    ]
