# Generated by Django 3.2 on 2021-11-21 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('index_name', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rule',
                'verbose_name_plural': 'Rules',
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_category', models.CharField(choices=[('any', 'any'), ('process', 'process'), ('network', 'network'), ('file', 'file'), ('registry', 'registry'), ('authentication', 'authentication'), ('configuration', 'configuration'), ('database', 'database'), ('driver', 'driver'), ('host', 'host'), ('iam', 'iam'), ('intrusion_detection', 'intrusion_detection'), ('malware', 'malware'), ('package', 'package'), ('session', 'session'), ('threat', 'threat'), ('web', 'web')], default='any', max_length=32)),
                ('condition', models.CharField(max_length=200)),
                ('by', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='rule.rule')),
            ],
            options={
                'verbose_name': 'Query',
                'verbose_name_plural': 'Queries',
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.BooleanField(default=False)),
                ('until', models.BooleanField(default=False)),
                ('maxspan', models.BooleanField(default=False)),
                ('size', models.BooleanField(default=False)),
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='rule.rule')),
            ],
        ),
    ]
