# Generated by Django 3.2 on 2021-11-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='query_sum',
            field=models.TextField(blank=True, default='query_sum', max_length=250, null=True),
        ),
    ]
