# Generated by Django 3.2 on 2021-11-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0002_rule_query_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='query_sum',
        ),
        migrations.AddField(
            model_name='rule',
            name='flag',
            field=models.CharField(blank=True, choices=[('create_rule', 'create_rule'), ('strategy', 'strategy')], max_length=250, null=True),
        ),
    ]
