# Generated by Django 3.2 on 2021-11-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0003_auto_20211123_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='total',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='flag',
            field=models.CharField(blank=True, choices=[('create_rule', 'create_rule'), ('strategy', 'strategy')], default='create_rule', max_length=250, null=True),
        ),
    ]
