# Generated by Django 3.2 on 2021-12-13 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0003_alter_order_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rule.rule'),
        ),
    ]
