# Generated by Django 3.2 on 2021-11-23 11:41

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0004_auto_20211123_1323'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='query',
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='rule',
            managers=[
                ('strategymanager', django.db.models.manager.Manager()),
            ],
        ),
    ]
