# Generated by Django 3.2 on 2021-11-23 11:50

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0005_auto_20211123_1511'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='rule',
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
