# Generated by Django 3.2 on 2021-11-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0006_alter_rule_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=100)),
                ('add_rule', models.CharField(max_length=100)),
                ('add_rule_manually', models.TextField(blank=True, null=True)),
                ('rule', models.ManyToManyField(related_name='strategy', to='rule.Rule')),
            ],
        ),
    ]
