# Generated by Django 3.2 on 2021-11-25 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0007_strategy'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='query',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='rule',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='rule',
            name='total',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='add_rule',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='add_rule_manually',
        ),
    ]
