# Generated by Django 3.2 on 2021-11-27 12:46

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0008_auto_20211125_1306'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='rule',
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
