# Generated by Django 3.2 on 2021-11-27 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0011_alter_rule_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='rule',
            managers=[
            ],
        ),
    ]
