# Generated by Django 3.2 on 2021-11-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0012_alter_rule_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='rule_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
