# Generated by Django 3.2 on 2021-11-29 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0015_rule_rule_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='rule_file',
        ),
    ]
