# Generated by Django 3.2 on 2021-11-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0016_remove_rule_rule_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategy',
            old_name='rule',
            new_name='rules',
        ),
    ]
