# Generated by Django 3.2 on 2021-11-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0017_rename_rule_strategy_rules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategy',
            options={'verbose_name': 'Strategy', 'verbose_name_plural': 'Strategies'},
        ),
    ]
