# Generated by Django 3.2 on 2021-12-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0018_alter_strategy_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='rules',
            field=models.ManyToManyField(to='rule.Rule'),
        ),
    ]
