# Generated by Django 3.2 on 2021-12-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0020_alter_strategy_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='rules',
            field=models.ManyToManyField(related_name='strategies', to='rule.Rule'),
        ),
    ]
