# Generated by Django 3.2 on 2021-12-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0022_alter_strategy_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
