# Generated by Django 3.2 on 2021-12-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0023_alter_rule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='total',
            field=models.TextField(blank=True, null=True),
        ),
    ]
